export const UPDATE_USER='UPDATE_USER';
export const CLEAR_USER='CLEAR_USER';
export const UPDATE_LOADING='UPDATE_LOADING';
export const UPDATE_BUYDATE='UPDATE_BUYDATE';
export const CLEAR_BUYDATE='CLEAR_BUYDATE';
